// Step ids are user-facing strings from workflow JSON, so kept as a plain alias
// to avoid friction at boundaries. SessionId and StepToken are internal handles
// generated by the agent runtime — brand them to prevent cross-use.
export type StepId = string;
export type SessionId = string & { readonly __brand: "SessionId" };
export type StepToken = string & { readonly __brand: "StepToken" };

export const asStepId = (s: string): StepId => s;
export const asSessionId = (s: string): SessionId => s as SessionId;
export const asStepToken = (s: string): StepToken => s as StepToken;
