#!/usr/bin/env bun
/**
 * Generate `src/infra/daemon/web-ui/web-assets.generated.ts` from the built
 * `web/dist`, emitting one `import … with { type: "file" }` per asset so that
 * `bun build --compile` embeds every file into the single binary. Run by the
 * `compile` npm script after `vite build`; the populated module is a transient
 * build artifact (the committed version is an empty stub).
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, posix } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const DIST = join(ROOT, "web", "dist");
const OUT = join(ROOT, "src", "infra", "daemon", "web-ui", "web-assets.generated.ts");
// Import specifiers are relative to the generated module's directory.
const OUT_DIR = join(ROOT, "src", "infra", "daemon", "web-ui");

// The committed empty stub — kept byte-for-byte identical so `--stub` (run by
// `compile` after building the binary) leaves the working tree clean.
const STUB = `// AUTO-GENERATED — do not edit by hand.
//
// This is the committed *stub*: it serves no UI, so a plain \`bun src/index.ts\`
// run and \`bun test\` behave as an API-only daemon. The \`compile\` npm script
// runs \`scripts/gen-web-assets.ts\` to overwrite this file with one \`with
// { type: "file" }\` import per built \`web/dist\` asset (embedded into the
// single binary), then restores this stub afterwards. See the plan/README.
export const WEB_ASSETS: { route: string; path: string; type: string }[] = [];
`;

if (process.argv.includes("--stub")) {
  writeFileSync(OUT, STUB, "utf8");
  console.log(`gen-web-assets: wrote empty stub to ${relative(ROOT, OUT)}`);
  process.exit(0);
}

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".otf": "font/otf",
  ".map": "application/json; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
  ".wasm": "application/wasm",
};

function contentType(file: string): string {
  const dot = file.lastIndexOf(".");
  const ext = dot >= 0 ? file.slice(dot).toLowerCase() : "";
  return CONTENT_TYPES[ext] ?? "application/octet-stream";
}

function walk(dir: string, files: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, files);
    else files.push(full);
  }
  return files;
}

const files = walk(DIST).sort();
if (files.length === 0) {
  throw new Error(`No files found under ${DIST}. Run \`bun run build:web\` first.`);
}

const imports: string[] = [];
const entries: string[] = [];
files.forEach((abs, i) => {
  const route = "/" + posix.normalize(relative(DIST, abs).split("\\").join("/"));
  // Relative specifier from the generated module to the dist file.
  const spec = relative(OUT_DIR, abs).split("\\").join("/");
  const id = `a${i}`;
  imports.push(`import ${id} from "${spec}" with { type: "file" };`);
  entries.push(
    `  { route: ${JSON.stringify(route)}, path: ${id}, type: ${JSON.stringify(
      contentType(abs),
    )} },`,
  );
});

const out = `// @ts-nocheck
// AUTO-GENERATED by scripts/gen-web-assets.ts — do not edit by hand.
// Populated build artifact (${files.length} embedded assets). The committed
// version of this file is an empty stub; \`bun run compile\` regenerates this
// and restores the stub afterwards.
${imports.join("\n")}

export const WEB_ASSETS: { route: string; path: string; type: string }[] = [
${entries.join("\n")}
];
`;

writeFileSync(OUT, out, "utf8");
console.log(`gen-web-assets: wrote ${files.length} embedded assets to ${relative(ROOT, OUT)}`);
